### ISSUE TITLE
在启动过程中的某些报错运作不正常

### ISSUE THREAD

**Issue by BAKAOLC** [Legacy-LuaSTG-Engine/LuaSTG-Sub#19]
在launch文件中的直接报错不会导致程序退出，而是在报错后继续启动程序（虽然实际并没有用，但一直会开着）

同时，在 [luajit/luajit#1021](https://github.com/LuaJIT/LuaJIT/issues/1021) 提出的问题会影响到引擎的工作，会在不触发任何报错的情况下直接导致引擎退出，同时在日志中无法查阅到任何信息（包括进行引擎销毁等行为），疑似直接导致引擎闪退而不是正常的报错退出流程

**Comment by Demonese** [comment]
已修复，等待反馈。
目前有个问题：stack traceback 看不到。
![image](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/assets/57629614/912824f1-4a75-4890-bf9f-5071c96ccc3c)

**Comment by BAKAOLC** [comment]
可以，能正确捕获到已经至少能保证用户不会完全的无头绪

**Comment by BAKAOLC** [comment]
很有效，孩子很喜欢
