### ISSUE TITLE
在协程中执行不允许的方法返回的报错信息不明确

### ISSUE THREAD

**Issue by BAKAOLC** [Legacy-LuaSTG-Engine/LuaSTG-Sub#20]
在协程中执行 lstg.DoFile 等类似方法会产生以下报错，报错消息为加载的目标文件，导致原因排查不明确
应当修正为 不允许在协程中执行本函数 等类似的消息
![Snipaste_2023-08-01_11-46-13](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/assets/35646643/7bd6d02d-2a48-4292-a1a7-1ff3065d8615)

**Comment by BAKAOLC** [comment]
另外，顺便一提，lua 原生的 dofile 等是不会出现这个情况的，最佳做法大概是得排查 DoFile 等类似函数为什么会出现错误（或者直接删除，用原生的替换）

**Comment by Demonese** [comment]
0.20.14已修复该问题
