### ISSUE TITLE
XAudio2 DLL loading broken on Linux/Wine

### ISSUE THREAD

**Issue by KaleiAlma** [Legacy-LuaSTG-Engine/LuaSTG-Sub#24]
XAudio2 fails to load under Linux/Wine (using [Kron4ek Wine 9.1](https://github.com/Kron4ek/Wine-Builds)) and leaves the exe running without audio.

The debug assertions fail in [LuaSTG/Platform/RuntimeLoader/All.cpp](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/blob/master/LuaSTG/Platform/RuntimeLoader/All.cpp), so it would make sense that the dll hacks placed there would be the cause.

Current release version of LuaSTG works perfectly with my Linux/Wine setup, including audio.

**Comment by KaleiAlma** [comment]
I tried undoing the XAudio parts of 6aa670e, and it works now. Still would be good to look into fixing this, as it seems you were trying to do something there?

**Comment by Demonese** [comment]
> I tried undoing the XAudio parts of [6aa670e](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/commit/6aa670e2ce57577add4b62a2a0dc9d7059eba8e2), and it works now. Still would be good to look into fixing this, as it seems you were trying to do something there?

I think you forgot to place the xaudio2_redist.dll file next to exe 2 days ago.

See release 0.20.1 [LuaSTG-Sub-v0.20.1.zip](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/releases/download/v0.20.1/LuaSTG-Sub-v0.20.1.zip)

**Comment by KaleiAlma** [comment]
No, it was always there... it just fails under wine for some reason.

**Comment by KaleiAlma** [comment]
Apparently my VM compile setup messes up dll loading, it works fine now that I compiled through Github Actions. Closing
