### ISSUE TITLE
BUG: Using _a/_r/_g/_b on an object with an advanced render class crashes the game

### ISSUE THREAD

**Issue by zinoLath** [Legacy-LuaSTG-Engine/LuaSTG-Sub#5]
When modifying an object's color using self._a, self._r, self._g and self._b (but not self._color), LuaSTG crashes with no error and no information on the .log file.
Code in image below: (zclass is identical to Class, however, it sets the [".render"] key of the class to true automatically, tests done on the code packaged with the latest release in Github, v0.18.10.)
![image](https://user-images.githubusercontent.com/58287992/184285180-a9cc54ac-e5b0-4e3f-ac77-2ba83e3fb827.png)
![image](https://user-images.githubusercontent.com/58287992/184285300-2f5f3122-0869-4b22-9f81-197ec0e34bc3.png)
The engine.log:
[engine.log](https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/files/9313669/engine.log)

**Comment by Demonese** [comment]
9534d9b1c55f0f519166b6090d34ab597d870d2b

**Comment by Demonese** [comment]
No response for over 30 days, I will close it
