### ISSUE TITLE
Silent crash when PostProcess is misused

### ISSUE THREAD

**Issue by zinoLath** [Legacy-LuaSTG-Engine/LuaSTG-Sub#8]
Using PostProcess(shdr,rt,id,blend,{ num1, num2, num3, num4 }) instead of PostProcess(shdr,rt,id,blend,{{ num1, num2, num3, num4 }}) causes the application to silently crash, without any errors or mention on engine.log.

**Comment by Demonese** [comment]
fixed 35b7daf947be6eefa097384e7dc06e0242e90bdf

**Comment by Demonese** [comment]
No response for over 30 days, I will close it
